# Cirrus workflow for testing on (Free)BSD.
#
# References:
#   - https://cirrus-ci.org/guide/writing-tasks/
#   - https://github.com/tokio-rs/tokio/blob/master/.cirrus.yml
#   - https://github.com/nix-rust/nix/blob/master/.cirrus.yml
#   - https://github.com/jakewilliami/HiddenFiles.jl/blob/master/.cirrus.yml
#
# TODO:
#   - Research best way to have different tests (one task with matrix or multiple tasks)
#   - Implement tests for other BSD OS's (will need to handle setup differently for Tier 3 support OS's)

# Set up environment variables
env:
  # The minimum supported Rust version (MSRV)
  # https://github.com/foresterre/cargo-msrv
  TOOLCHAIN: 1.56.1

# Define set up procedure by downloading Rustup (to consume later)
setup_common: &SETUP
  setup_script:
    - kldload mqueuefs
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain $TOOLCHAIN
    - . $HOME/.cargo/env || true
    - cargo -Vv
    - rustc -Vv

# Cache the Cargo directory between runs
cargo_cache:
  folder: $CARGO_HOME/registry
  fingerprint_script: cat Cargo.lock || echo ""

task:
  # Specify container (FreeBSD): https://cirrus-ci.org/guide/writing-tasks/#execution-environment
  freebsd_instance:
    image: freebsd-13-1-release-amd64  # freebsd-12-3-release-amd64

  # Set up Rust environment using Rustup
  <<: *SETUP

  matrix:
    # Run Unit Tests
    - name: "Runs \"cargo test\" on FreeBSD 13"
      test_script:
        - cargo test --all --all-features -- --nocapture -D warnings
        - cargo doc --no-deps --target $TARGET
      before_cache_script: rm -rf $CARGO_HOME/registry/index

    # Test Cargo Build
    - name: "Builds on FreeBSD 13"
      test_script: cargo build +$TOOLCHAIN --release --target $TARGET --all-targets

    # Test Cargo Clippy
    - name: "Runs \"cargo clippy\" on FreeBSD 13"
      install_script: rustup component add --toolchain $TOOLCHAIN clippy
      test_script: cargo clippy --target $TARGET --all-targets -- -D warnings

    # Test Cargo Fmt
    - name: "Runs \"cargo fmt\" on FreeBSD 13"
      install_script: rustup +$TOOLCHAIN component add rustfmt
      test_script: cargo fmt --all -- --check

    # Test Cargo Publish
    - name: "Runs \"cargo publish --dry-run\" on FreeBSD 13"
      test_script: cargo publish --dry-run
