name: clippy
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  clippy:
    name: Runs "cargo clippy" on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macOS-latest
        ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Cache .cargo and target
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ./target
          key: ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-clippy

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
